module.exports={
	port:4000,
	apiPort:4001,
	host:"localhost",
	user:'root',
	password:'123',
	database:'react-eval',
	basicURL_T:'http://localhost:4000/teacher',
	basicURL_S:'http://localhost:4000/student',
	basicURL:'http://localhost:4000'
};